context:
  name: langchain-ollama
  version: "0.3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_ollama-${{ version }}.tar.gz
  sha256: 5d942d331c44351bae5c5c5965603ceb20b0ee4d70082290f4b15bc638559756

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - ollama-python >=0.5.3,<1.0.0
    - langchain-core <1.0.0,>=0.3.76

tests:
  - python:
      imports:
        - langchain_ollama
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: An integration package connecting Ollama and LangChain
  license: MIT
  license_file: LICENSE
  repository: https://github.com/langchain-ai/langchain/blob/master/libs/partners/ollama/
  homepage: https://python.langchain.com/docs/integrations/providers/ollama/

extra:
  recipe-maintainers:
    - MridulS
