context:
  name: langchain-ollama
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_ollama-${{ version }}.tar.gz
  sha256: 2ea9ad1b0f0ab319d600b9193d1124a8925523a3b943d75a967718e24ec09a8a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - ollama-python >=0.6.0,<1.0.0
    - langchain-core >=1.0.0,<2.0.0

tests:
  - python:
      imports:
        - langchain_ollama
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: An integration package connecting Ollama and LangChain
  license: MIT
  license_file: LICENSE
  repository: https://github.com/langchain-ai/langchain/blob/master/libs/partners/ollama/
  homepage: https://python.langchain.com/docs/integrations/providers/ollama/

extra:
  recipe-maintainers:
    - MridulS
